version: '3.8'

networks:
  backend-network:
    driver: bridge

services:
  main_db:
    image: postgres:15
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${MAIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${MAIN_DB_PASSWORD}
      POSTGRES_DB: ${MAIN_DB}
    networks:
      - backend-network
    ports:
      - '${MAIN_DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend-network
    ports:
      - '6379:6379'

  core_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - main_db
      - redis
    networks:
      - backend-network
volumes:
  postgres_data: {}
